/**
 *
 * $Id$
 */
package org.tetrabox.minijava.xminijava.miniJava.validation;

import org.tetrabox.minijava.xminijava.miniJava.Call;
import org.tetrabox.minijava.xminijava.miniJava.Context;
import org.tetrabox.minijava.xminijava.miniJava.Frame;
import org.tetrabox.minijava.xminijava.miniJava.ObjectInstance;
import org.tetrabox.minijava.xminijava.miniJava.Value;

/**
 * A sample validator interface for {@link org.tetrabox.minijava.xminijava.miniJava.Frame}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface FrameValidator {
	boolean validate();

	boolean validateCall(Call value);
	boolean validateInstance(ObjectInstance value);
	boolean validateChildFrame(Frame value);
	boolean validateParentFrame(Frame value);
	boolean validateRootContext(Context value);
	boolean validateReturnValue(Value value);
}
