/**
 *
 * $Id$
 */
package org.tetrabox.minijava.xminijava.miniJava.validation;

import org.eclipse.emf.common.util.EList;

import org.tetrabox.minijava.xminijava.miniJava.Import;
import org.tetrabox.minijava.xminijava.miniJava.State;
import org.tetrabox.minijava.xminijava.miniJava.TypeDeclaration;

/**
 * A sample validator interface for {@link org.tetrabox.minijava.xminijava.miniJava.Program}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ProgramValidator {
	boolean validate();

	boolean validateName(String value);
	boolean validateImports(EList<Import> value);
	boolean validateClasses(EList<TypeDeclaration> value);
	boolean validateState(State value);
}
