/**
 *
 * $Id$
 */
package org.tetrabox.minijava.xminijava.miniJava.validation;

import org.eclipse.emf.common.util.EList;

import org.tetrabox.minijava.xminijava.miniJava.AccessLevel;
import org.tetrabox.minijava.xminijava.miniJava.Interface;
import org.tetrabox.minijava.xminijava.miniJava.Member;

/**
 * A sample validator interface for {@link org.tetrabox.minijava.xminijava.miniJava.TypeDeclaration}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface TypeDeclarationValidator {
	boolean validate();

	boolean validateAccessLevel(AccessLevel value);
	boolean validateImplements(EList<Interface> value);
	boolean validateMembers(EList<Member> value);
}
