/**
 *
 * $Id$
 */
package org.tetrabox.minijava.dynamic.minijavadynamicdata.validation;

import org.tetrabox.minijava.dynamic.minijavadynamicdata.ArrayInstance;

/**
 * A sample validator interface for {@link org.tetrabox.minijava.dynamic.minijavadynamicdata.ArrayRefValue}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ArrayRefValueValidator {
	boolean validate();

	boolean validateInstance(ArrayInstance value);
}
